type Question {
    id: ID!
    theme: Theme!
    question: String!
    options: [String!]
    answer: String!
    explanation: String
    links: [String!]
    nb_answered: Int
    nb_success: Int
    created_at: Date
    updated_at: Date
}

type Query {
    questions: [Question]
}

type Mutation {
    addQuestion(args: AddQuestionInput): Question
    editQuestion(args: EditQuestionInput): Question
    updateSuccessRate(args: SuccessRateInput): Float
}

input AddQuestionInput {
    theme_id: String!
    question: String!
    options: [String!]!
    answer: String!
    explanation: String
    links: [String!]
}

input EditQuestionInput {
    theme_id: String
    question: String
    options: [String!]
    answer: String
    explanation: String
    links: [String!]
}

input SuccessRateInput {
    good_answer: booleanls
}
